// <auto-generated />
namespace ORM_AugustinRibreau.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MigrationForTestLiaisonWithHistoryAndIntervener : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrationForTestLiaisonWithHistoryAndIntervener));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121307231_MigrationForTestLiaisonWithHistoryAndIntervener"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
